# Generated by Django 3.2.7 on 2021-10-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_auto_20211007_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['updated_at']},
        ),
    ]
