# Generated by Django 3.2.7 on 2021-10-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0002_alter_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
