# Generated by Django 3.2.7 on 2021-10-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0005_auto_20211007_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='caretaker_status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('busy', 'busy')], max_length=9, null=True),
        ),
    ]
