# Generated by Django 3.2.7 on 2021-10-07 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketconversation',
            name='caretakerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caretaker_ids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketconversation',
            name='customerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_ids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketconversation',
            name='ticketId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Ticket.ticket'),
        ),
    ]
