# Generated by Django 3.2.7 on 2021-10-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_auto_20211007_2050'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticketassign',
            table='ticket_assign',
        ),
    ]
