# Generated by Django 3.2.7 on 2021-10-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0006_alter_ticketassign_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketassign',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='ticketassign',
            unique_together=set(),
        ),
    ]
