# Generated by Django 3.2.7 on 2021-10-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0013_alter_ticketassign_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignStatus',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
