# Generated by Django 3.2.7 on 2021-10-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0014_ticket_assignstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketconversation',
            name='message',
            field=models.TextField(max_length=200),
        ),
    ]
