# Generated by Django 3.2.7 on 2021-10-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0015_alter_ticketconversation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketconversation',
            old_name='caretakerId',
            new_name='caretaker_id',
        ),
        migrations.RenameField(
            model_name='ticketconversation',
            old_name='customerId',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='ticketconversation',
            old_name='ticketId',
            new_name='ticket_id',
        ),
    ]
