# Generated by Django 3.2.7 on 2021-10-24 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ticket', '0017_auto_20211011_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketconversation',
            name='caretaker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_ids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketconversation',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_ids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketconversation',
            name='msg_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ticketassign',
            unique_together={('ticketId', 'customerId')},
        ),
    ]
