# Generated by Django 3.2.7 on 2021-10-24 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0018_auto_20211024_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketconversation',
            name='ticket_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convoTicketId', to='Ticket.ticket'),
        ),
    ]
